# Generated by Django 4.1.6 on 2023-02-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-done', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='not_relevant_tags',
            new_name='relevant_tags',
        ),
    ]
